### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by MELAS007** [kacepe/ng2-ago#1]
HI!

I did as you told in the instruction then i got error : 

[09:39:13]  build started ...
[09:39:13]  transpile started ...
[09:39:15]  typescript: D:/EDUMASR/mobile apps/HSC/mobile2/node_modules/ng2-ago/index.ts, line: 5
            Module '"D:/EDUMASR/mobile
            apps/HSC/mobile2/node_modules/@angular/common/src/pipes/invalid_pipe_argument_error"' has no exported member
            'InvalidPipeArgumentError'.

       L4:  import { DateFormatter } from '@angular/common/src/pipes/intl';
       L5:  import { InvalidPipeArgumentError } from '@angular/common/src/pipes/invalid_pipe_argument_error';

i use ionic 3 and angular 4 and node v6.10.2

what can i do?

thanks

**Comment by kvcpr** [comment]
This package is outdated and doesn't support angular 4. I recommend to use moment.js.
